name: Copy Files to VPS

# Kapan workflow ini dijalankan
on:
  push:
    branches: [ "main", "master" ] # atau "master", sesuai dengan branch utama Anda

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # Tambahkan ini untuk pakai Node 24


jobs:
  deploy:
    runs-on: ubuntu-latest # Menggunakan runner dari GitHub
    steps:
      # 1. Ambil kode terbaru dari repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Hubungkan ke VPS dan jalankan perintah deployment
      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.VPS_HOST }} # IP server Anda
          username: ${{ vars.VPS_USERNAME }} # Username SSH, misal 'root' atau 'ubuntu'
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }} # Kunci privat yang sudah disimpan
          port: 22101 # Port SSH Anda
          source: "."
          target: "mnt/bdone4-storage/database/fanfirst-db"  # tujuan di VPS
